version: '3.9'
services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000 
    depends_on:
      - nestapp
  