version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: globalline/nestapp:1.0.0
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db 
      - PG_USER=globalline
      - PG_PASSWORD=20Global10
      - PG_DB=globalline
      - PG_PORT=5432
  
